#!/usr/bin/env python3
"""Regenerate phonon/requirements.lock and phonon/requirements-torch.lock.

Reads the exact pins in phonon/requirements.in (everything except torch) and
TORCH_VERSION below, then writes `--hash=sha256:` lines for every
CPython-3.12 / x86-64-Linux / pure-Python wheel of each pinned version, taken
from PyPI's JSON API (and, for torch, the PyTorch CPU wheel index). The image
build installs with `--require-hashes --only-binary=:all: --no-deps`, so a
substituted or tampered file cannot be installed.

Stdlib only. Needs network. Run it inside a throwaway container, e.g.:

    podman run --rm -v "$PWD":/w -w /w docker.io/library/python:3.12-slim-trixie \\
        python scripts/update-phonon-lock.py

Review the diff before committing: it is the trust anchor for what gets installed.
"""
import json, re, sys, time, urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent / "phonon"
TORCH_VERSION = "2.14.1+cpu"
TORCH_INDEX = "https://download.pytorch.org/whl/cpu/torch/"


def get(url, attempts=5):
    for i in range(attempts):
        try:
            with urllib.request.urlopen(url, timeout=60) as r:
                return r.read().decode()
        except OSError as e:
            if i == attempts - 1:
                raise
            print(f"retrying {url} ({e})", file=sys.stderr)
            time.sleep(2 ** i)


def wanted(filename):
    """CPython 3.12 (or abi3 / pure-Python) wheels usable on x86-64 glibc Linux."""
    if not filename.endswith(".whl"):
        return False
    parts = filename[:-4].split("-")
    py, abi, plat = parts[-3], parts[-2], parts[-1]
    if not (py in ("cp312", "py3", "py2.py3", "py3.12") or (abi == "abi3" and py.startswith("cp3"))):
        return False
    if abi == "abi3" and py.startswith("cp3") and int(py[3:]) > 12:
        return False
    if plat == "any":
        return True
    return "x86_64" in plat and ("manylinux" in plat or "linux" == plat.split("_")[0])


def pypi_hashes(name, version):
    data = json.loads(get(f"https://pypi.org/pypi/{name}/{version}/json"))
    hashes = sorted({f["digests"]["sha256"] for f in data["urls"] if wanted(f["filename"])})
    if not hashes:
        sys.exit(f"no usable wheel for {name}=={version}")
    return hashes


def torch_hashes():
    html = get(TORCH_INDEX)
    want = TORCH_VERSION.replace("+", "%2B")
    out = set()
    for m in re.finditer(r'href="[^"]*?/(torch-[^"#/]+\.whl)#sha256=([0-9a-f]{64})"', html):
        fn, h = m.group(1), m.group(2)
        if fn.startswith(f"torch-{want}-") and wanted(fn.replace("%2B", "+")):
            out.add(h)
    if not out:
        sys.exit("no usable torch wheel found on the PyTorch CPU index")
    return sorted(out)


def render(header, entries):
    lines = header
    for req, hashes in entries:
        lines.append(f"{req} \\")
        lines.extend(f"    --hash=sha256:{h}" + (" \\" if i < len(hashes) - 1 else "") for i, h in enumerate(hashes))
    return "\n".join(lines) + "\n"


def main():
    pins = [l.strip() for l in (ROOT / "requirements.in").read_text().splitlines() if l.strip() and not l.startswith("#")]
    entries = []
    for pin in pins:
        name, version = pin.split("==")
        entries.append((pin, pypi_hashes(name, version)))
        print(f"{pin}: {len(entries[-1][1])} hashes", file=sys.stderr)
    header = ["# GENERATED by scripts/update-phonon-lock.py from requirements.in. Do not edit.",
              "--index-url https://pypi.org/simple"]
    (ROOT / "requirements.lock").write_text(render(header, entries))
    th = torch_hashes()
    print(f"torch=={TORCH_VERSION}: {len(th)} hashes", file=sys.stderr)
    header = ["# GENERATED by scripts/update-phonon-lock.py. Do not edit.",
              "--index-url https://download.pytorch.org/whl/cpu"]
    (ROOT / "requirements-torch.lock").write_text(render(header, [(f"torch=={TORCH_VERSION}", th)]))


main()
